name: Run Python Script

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间 6 点
    - cron: '0 6 * * *'    # 北京时间 14 点
    - cron: '0 12 * * *'   # 北京时间 20 点
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: LIFISHER_SECRETS  # 指定环境名称
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间 (UTC+8)
    steps:
      - uses: actions/checkout@v3  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python assign_inquiry.py
        env:
          LIFISHER_CODES: ${{ secrets.LIFISHER_CODES }}
          LIFISHER_TOKEN: ${{ secrets.LIFISHER_TOKEN }}
          LIFISHER_VARIABLES: ${{ vars.LIFISHER_VARIABLES }}
          LIFISHER_STAFF_CODES: ${{ vars.LIFISHER_STAFF_CODES }}

      - name: Notify on success
        if: success()
        run: |
          echo "Script ran successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Script failed!"
